import type { Metadata } from "next";

import "@/styles/globals.css";

import { Locale , i18n} from '@/i18n.config'

import Navbar from "@/components/Navbar";
import Whatsapp from "@/components/Whatsapp";

export const metadata: Metadata = {
  title: "Erişim Kablo",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({lang: locale}))
}

export default function RootLayout(
{
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { lang : Locale}
}>) {
  return (
    <html lang={params.lang}>
      <body>
        <Navbar lang={params.lang}/>
        <main>{children}</main>
        <Whatsapp />
      </body>
    </html>
  );
}
